services:
  mongodb-master:
    image: mongo
    container_name: mongodb-master
    command:
      [
        "--replSet",
        "rs0",
        "--dbpath",
        "/data/db",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongodb/pki/keyfile",
      ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - ./mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./mongo/master/db:/data/db
      - ./mongo/master/configdb:/data/configdb
    ports:
      - "27017:27017"
    networks:
      - mongo-network

  mongodb-slave:
    image: mongo
    container_name: mongodb-slave
    command:
      [
        "--replSet",
        "rs0",
        "--dbpath",
        "/data/db",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongodb/pki/keyfile",
      ]
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    volumes:
      - ./mongo/rs_keyfile:/etc/mongodb/pki/keyfile
      - ./mongo/slave/db:/data/db
      - ./mongo/slave/configdb:/data/configdb
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge

volumes:
  mongodb-master-data:
  mongodb-slave-data:
