services:
  pg-master:
    build:
      dockerfile: Dockerfile.postgresql10
      
    container_name: pg-master
    volumes:
      - pg-master-data:/var/lib/postgresql/data
      - ./master-data:/var/lib/postgresql/data
    networks:
      - db-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db

  pg-slave:
    image: postgres:15
    container_name: pg-slave
    volumes:
      - pg-slave-data:/var/lib/postgresql/data
      - ./slave-data:/var/lib/postgresql/data
    networks:
      - db-network
    environment:
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=test_db

networks:
  db-network:

volumes:
  pg-master-data:
  pg-slave-data:
